### ISSUE TITLE
Failed after first layer

### ISSUE THREAD

**Issue by HalyconExport** [SumolX/FlashForge#2]
First of all, I love this project and is my only answer to using this flash forge printer.
the first layer prints fine, but and the end of it, it glitches out, does a little blob then continues onto the second layer but does extrude filament until halfway through the second layer. I believe the guy on the prusa platform forum for this had the same problem just a bigger blob. Please I want this to work and get in touch with me for a video or picture

**Comment by HalyconExport** [comment]
It seems to be an issue with retraction happening when that commences.. I can change where it will retract and it does the blob and non-extrude after that.

**Comment by SumolX** [comment]
Please join the following group and reach out to me via messenger so we can discuss this in further detail.

https://www.facebook.com/groups/932523481002927

I have a few ideas as to how we can debug this issue.  Both of us having an identical STL and generating the gcode.  This will allow me to compare the output of both our files.
