### ISSUE TITLE
i Have the scipt in the right folder but cura wont show it in modify g code

### ISSUE THREAD

**Issue by camolot13** [SumolX/FlashForge#3]
Idk what to do tried everything i hate flash print have horrible print seams and cant get them fixed withere there settings

**Comment by SumolX** [comment]
I haven't played with Cura in a while.  I will look into it.  Which version of Cura do you have installed?

**Comment by SumolX** [comment]
I have updated the readme and deprecated FlashForgeAdapter.py as it is not needed once you follow the Post Processing instructions and install GXWriter from Marketplace. As for the cura profiles... I am reworking them and will upload them when I have results that are satisfactory.
