### ISSUE TITLE
I cannot add the profile in Cura

### ISSUE THREAD

**Issue by Beldar84** [SumolX/FlashForge#4]
I use Cura 4.10 on Mac (it is the highest version I can select with my OS), and after following your steps and installing the script, when I go to import the profile it tells me:

Error importing profile from /Downloads/FlashForge-main 2/Cura/Profiles/FFA4_Draft.curaprofile: Unable to add profile.

Any solution?

**Comment by SumolX** [comment]
I have updated the readme and deprecated FlashForgeAdapter.py as it is not needed once you follow the Post Processing instructions and install GXWriter from Marketplace.  As for the cura profiles... I am reworking them and will upload them when I have results that are satisfactory.
